repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: check-yaml
    args:
      - "--unsafe"
  - id: requirements-txt-fixer
    files: ^requirements/.*$

- repo: local
  hooks:
    - id: black
      name: Black
      entry: black
      args:
        - '-S'
      language: python
      types:
        - python

    - id: pylint
      name: PyLint
      entry: pylint
      language: python
      types:
        - python

    - id: autoflake
      name: Remove unused imports
      entry: autoflake
      language: python
      args:
        - '--in-place'
        - '--remove-all-unused-imports'
      types:
        - python

    - id: flake8
      name: Flake8
      entry: flake8
      language: python
      types:
        - python
