---
- name: Get current timezone
  ansible.builtin.command: timedatectl show --property=Timezone --value
  register: timezone_output
  changed_when: false

- name: Prepare Dockerfile
  template:
    dest: "/tmp/Dockerfile"
    src: "Dockerfile.j2"

- name: Create volume directory for a container
  file:
    path: "{{ docker_lib_folder }}/volumes/meow-bot/sources"
    recurse: yes
    state: directory
    owner: root
    group: root
  become: yes

- name: Copy req.txt for building a docker image
  copy:
    dest: "/tmp/prod.txt"
    src: "../../../../requirements/prod.txt"

- name: Copy sources
  synchronize:
    dest: "{{ docker_lib_folder }}/volumes/meow-bot/sources"
    src: "../../../../sources/"
    owner: false
    group: false
  become: yes

- name: Build a docker image
  docker_image:
    name: "discord-meow-bot"
    force_source: yes
    build:
      path: "/tmp"
      pull: yes
      network: host
    source: build
  become: yes

- name: Up a docker container
  docker_container:
    name: "discord-meow-bot"
    image: "discord-meow-bot"
    state: started
    restart_policy: always
    restart: yes
    mounts:
      - source: "{{ docker_lib_folder }}/volumes/meow-bot/sources"
        target: "/code/sources"
        read_only: yes
        type: bind
  become: yes

- name: Remove Dockerfile
  file:
    path: "/tmp/Dockerfile"
    state: absent
...
